version: '3'
services:
  auth_api:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  tests:
    build: ./tests/functional/
    entrypoint: sh -c "sleep 5 && pytest -s ./src"
    depends_on:
      - auth_api

  db:
    image: postgres:13
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./db/.pgdata:/var/lib/postgresql/data/
    env_file: ./flask_app/.env

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"